# Nome da sua aplicacao
spring.application.name=instagram-clone

# Configuracoes do Banco de Dados H2 (Roda na memoria)
spring.datasource.url=jdbc:h2:mem:instadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Ativa o Console do H2 (E isso que resolve o seu Erro 404)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Faz o Hibernate criar as tabelas automaticamente e mostra os comandos no terminal
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
api.security.token.secret=${JWT_SECRET:6e897df4-399a-4131-893d-d8b3c75d71c2}