# Nome do projeto
spring.application.name=instagram-clone

# Configurações do Banco de Dados H2 (Roda na memória)
spring.datasource.url=jdbc:h2:mem:instadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Ativa o Console do H2 (Para você ver as tabelas no seu navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Faz o Hibernate criar as tabelas automaticamente baseado no seu desenho do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
